// <auto-generated />
namespace eSektör.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _26062019_1602 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_26062019_1602));
        
        string IMigrationMetadata.Id
        {
            get { return "201906261302480_26062019_1602"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
