// <auto-generated />
namespace eSektör.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _04072019_1450 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_04072019_1450));
        
        string IMigrationMetadata.Id
        {
            get { return "201907041151193_04072019_1450"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
