// <auto-generated />
namespace eSektör.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _1806_1755 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1806_1755));
        
        string IMigrationMetadata.Id
        {
            get { return "201906181455390_1806_1755"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
